language: android
jdk:
  - oraclejdk8
branches:
  only:
  - master
env:
  global:
    - ANDROID_TARGET=android-23
    - ANDROID_ABI=google_apis/armeabi-v7a
    
before_install:
  - mkdir -p $ANDROID_HOME/licenses
  - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_HOME/licenses/android-sdk-license
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> $ANDROID_HOME/licenses/android-sdk-license
install:
  - echo y | sdkmanager "ndk-bundle"
  - echo y | sdkmanager "cmake;3.6.4111459"
  - echo y | sdkmanager "lldb;3.1"

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - $ANDROID_TARGET
    - extra-android-m2repository
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
    
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

before_script:
  - wget https://github.com/opencv/opencv/releases/download/3.4.1/opencv-3.4.1-android-sdk.zip
  - unzip -q opencv-3.4.1-android-sdk.zip
  - export OPENCV_ANDROID_SDK=$(pwd)/OpenCV-android-sdk
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
- cd FaceTracker
- ./gradlew build
- ./gradlew connectedReleaseAndroidTest

