language: android
jdk:
  - oraclejdk8
branches:
  only:
  - master
env:
  global:
    - ANDROID_TARGET=android-23
    - ANDROID_ABI=armeabi-v7a
    
before_install:
  - mkdir -p $ANDROID_HOME/licenses
  - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_HOME/licenses/android-sdk-license
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> $ANDROID_HOME/licenses/android-sdk-license
install:
  - echo y | sdkmanager "ndk-bundle"
  - echo y | sdkmanager "cmake;3.6.4111459"
  - echo y | sdkmanager "lldb;3.1"

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-23
    - extra-android-m2repository
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

before_install:
  - echo $(ant -version)

script:
- cd visionSamples/FaceTracker/
- ./gradlew build

